#! /bin/sh
### BEGIN INIT INFO
# Provides:          Autostarts liota.
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Starts liotad.py in background at reboot.
### END INIT INFO

. /etc/liota/packages

PATH=/sbin:/usr/sbin:/bin:/usr/bin

do_start() {
	sudo python /etc/liota/packages/liotad.py &
}

case "$1" in
    start)
	do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

